local_costmap:
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  global_frame: $(arg odom_frame)
  update_frequency: 5.0
  publish_frequency: 2.0
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05
  obstacle_layer:
    observation_sources: laser_scan_sensor
    obstacle_range: 2.5
    raytrace_range: 3.0
    laser_scan_sensor:
      sensor_frame: $(arg robot_name)/front_lidar_link
      topic: front_lidar/scan
      data_type: LaserScan
      marking: true
      clearing: true
  inflation_layer:
    inflation_radius: 0.2
    # footprint: [
    #   [0.35, 0.2],
    #   [0.35, -0.2],
    #   [-0.35, -0.2],
    #   [-0.35, 0.2]
    # ]
